apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gelift-tracker
spec:
  entryPoints:
    - websecure
  tls: {}
  routes:
    - match: "Host(`gelift.gewis.nl`)"
      kind: Rule
      services:
        - name: gelift-tracker
          port: 80